version: '3.9'

services:
    web-app:
        container_name: diplom_app
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./:/app
        env_file:
            - .env

    redis:
        image: redis:alpine
        restart: always

    worker:
        build: ./
        hostname: worker
        entrypoint: celery
        command: -A celery_app.app worker --loglevel=info
        volumes:
            - ./:/app
        depends_on:
            - redis