version: '3.9'

services:
    web-app:
        container_name: diplom_app
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        env_file:
            - .env

    redis:
        image: redis:alpine
        hostname: redis
        restart: always

    worker:
        build:
            context: .
        hostname: worker
        entrypoint: celery
        command: -A netology_pd_diplom worker --loglevel=info
        volumes:
            - .:/app
        depends_on:
            - web-app
            - redis

    flower:
        build:
            context: .
        hostname: flower
        entrypoint: celery
        command: -A netology_pd_diplom flower
        volumes:
            - .:/app
        depends_on:
          - redis
        ports:
          - "5555:5555"